[package]
name = "chainflip-btc-deposit-tracker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
async-trait = "0.1.73"
futures = "0.3.28"
jsonrpsee = { version = "0.16.2", features = ["server"] }
reqwest = { version = "0.11.18", features = ["json"] }
serde = "1.0.183"
tokio = "1.29.1"
tracing = "0.1.34"
tracing-subscriber = { version = "0.3.3", features = ["env-filter"] }
tempfile = "3.8"

sp-core = { git = "https://github.com/chainflip-io/substrate.git", tag = "chainflip-monthly-2023-08+2" }
codec = { package = "parity-scale-codec", version = "3.6.1", features = [
  "derive",
  "full",
] }

# Local dependencies
chainflip-engine = { path = "../../../engine/"}
utilities = { path = "../../../utilities" }
cf-primitives = { path = "../../../state-chain/primitives" }
pallet-cf-environment = { path = "../../../state-chain/pallets/cf-environment" }
state-chain-runtime = { path = "../../../state-chain/runtime" }
