# Default configurations for the CFE
[node_p2p]
node_key_file = "./localnet/init/secrets/node_key_file"
ip_address = "127.0.0.1"
port = 8078
allow_local_ip = true

[state_chain]
# 32 byte hex secret key - associated with the node's public id (public key)
signing_key_file = "./localnet/init/secrets/signing_key_file"
ws_endpoint = "ws://localhost:9944"

[eth]
# Ethereum private key file path. Default is the docker secrets path. This file should contain a hex-encoded private key.
private_key_file = "./localnet/init/secrets/eth_private_key_file"
ws_node_endpoint = "ws://localhost:8546"
http_node_endpoint = "http://localhost:8545"

[health_check]
hostname = "0.0.0.0"
port = 5555

[signing]
db_file = "/tmp/chainflip/bashful.db"

[dot]
ws_node_endpoint = "ws://localhost:9945"

[btc]
http_node_endpoint = "http://localhost:8332"
rpc_user = "flip"
rpc_password = "flip"