# Default configurations for the CFE
[node_p2p]
#node_key_file = "./keys/node_key_file"
ip_address = "127.0.0.1"
#port = 8078
allow_local_ip = true

#[state_chain]
# 32 byte hex secret key - associated with the node's public id (public key)
#signing_key_file = "./keys/signing_key_file"
#ws_endpoint = "ws://localhost:9944"

#[eth]
# Ethereum private key file path. Default is the docker secrets path. This file should contain a hex-encoded private key.
#private_key_file = "./keys/eth_private_key_file"

[eth.rpc]
ws_endpoint = "ws://localhost:8546"
http_endpoint = "http://localhost:8545"

# optional
#[eth.backup_rpc]
#ws_endpoint = "ws://localhost:8555"
#http_endpoint = "http://localhost:8555"

# DEPRECATED - dot settings will be removed in a future release.
[dot.rpc]
ws_endpoint = "ws://localhost:9947"
http_endpoint = "http://localhost:9947"

# optional
[dot.backup_rpc]
ws_endpoint = "ws://localhost:9948"
http_endpoint = "http://localhost:9948"

[hub.rpc]
ws_endpoint = "ws://localhost:9955"
http_endpoint = "http://localhost:9955"

# optional
#[hub.backup_rpc]
#ws_endpoint = "ws://localhost:8000"
#http_endpoint = "http://localhost:8000"

[btc.rpc]
http_endpoint = "http://localhost:8332"
basic_auth_user = "flip"
basic_auth_password = "flip"

# optional
#[btc.backup_rpc]
# http_endpoint = "http://localhost:8332"
# basic_auth_user = "flip"
# basic_auth_password = "flip"

[arb.rpc]
ws_endpoint = "ws://localhost:8548"
http_endpoint = "http://localhost:8547"

# optional
#[arb.backup_rpc]
#ws_endpoint = "ws://localhost:8548"
#http_endpoint = "http://localhost:8547"

[sol.rpc]
http_endpoint = "http://localhost:8899"

# optional
# [sol.backup_rpc]
# http_endpoint = "http://localhost:8899"


# No need for ws (TRON doesn't support it anyway). Separating
# endpoints as sme rpc providers may offer only one or the other
# plus the ones that offer both have different endpoints for each.
[tron.rpc]
http_endpoint = "http://localhost:8090" # For `getBlockBalance`. Needs archival node.
json_rpc_endpoint = "http://localhost:8091" # For `eth_getLogs`

# optional
#[tron.backup_rpc]
#ws_endpoint = "ws://localhost:8548"
#http_endpoint = "http://localhost:XXXX"

# optional
[health_check]
hostname = "0.0.0.0"
#port = 5555

# optional
#[prometheus]
#hostname = "0.0.0.0"
#port = 5566

#[signing]
#db_file = "/tmp/chainflip/bashful.db"

[logging]
command_server_port = 4321
