# Default configurations for the CFE
[node_p2p]
node_key_file = "./localnet/init/keys/node_key_file"
ip_address = "127.0.0.1"
port = 8078
allow_local_ip = true

[state_chain]
# 32 byte hex secret key - associated with the node's public id (public key)
signing_key_file = "./localnet/init/keys/signing_key_file"
ws_endpoint = "ws://localhost:9944"

[eth]
# Ethereum private key file path. Default is the docker secrets path. This file should contain a hex-encoded private key.
private_key_file = "./localnet/init/keys/eth_private_key_file"

[eth.rpc]
ws_endpoint = "ws://localhost:8546"
http_endpoint = "http://localhost:8545"

# optional
#[eth.backup_rpc]
#ws_endpoint = "ws://localhost:8555"
#http_endpoint = "http://localhost:8555"

[dot.rpc]
ws_endpoint = "ws://localhost:9945"
http_endpoint = "http://localhost:9945"

# optional
#[dot.backup_rpc]
#ws_endpoint = "ws://localhost:8000"
#http_endpoint = "http://localhost:8000"

[btc.rpc]
http_endpoint = "http://localhost:8332"
basic_auth_user = "flip"
basic_auth_password = "flip"

# optional
#[btc.backup_rpc]
# http_endpoint = "http://localhost:8332"
# basic_auth_user = "flip"
# basic_auth_password = "flip"

# optional
[health_check]
hostname = "0.0.0.0"
port = 5555

# optional
[prometheus]
hostname = "0.0.0.0"
port = 5566

[signing]
db_file = "/tmp/chainflip/bashful.db"
