[package]
name = "cf-test-utilities"
version = "0.1.0"
edition = "2018"
authors = ['Chainflip <https://chainflip.io>']
description = "Chainflip test utilities used in multiple crates"

[dependencies.frame-system]
git = 'https://github.com/chainflip-io/substrate.git'
tag = 'chainflip-monthly-2022-05'

[features]
default = ['std']
std = [
    'frame-system/std',
]