[package]
name = 'cf-test-utilities'
version = '0.1.0'
edition = '2021'
authors = ['Chainflip <https://chainflip.io>']
description = 'Chainflip test utilities used in multiple crates'

[dependencies]
codec = { package = 'parity-scale-codec', version = '3.6.1' }

frame-support = { git = "https://github.com/chainflip-io/polkadot-sdk.git", tag = "chainflip-substrate-1.1+2" }
frame-system = { git = "https://github.com/chainflip-io/polkadot-sdk.git", tag = "chainflip-substrate-1.1+2" }

sp-io = { git = "https://github.com/chainflip-io/polkadot-sdk.git", tag = "chainflip-substrate-1.1+2" }
sp-core = { git = "https://github.com/chainflip-io/polkadot-sdk.git", tag = "chainflip-substrate-1.1+2" }
sp-runtime = { git = "https://github.com/chainflip-io/polkadot-sdk.git", tag = "chainflip-substrate-1.1+2" }

[dev-dependencies]
scale-info = { version = "2.5.0", features = ["derive"] }
