[package]
name = 'cf-test-utilities'
version = '0.1.0'
edition = '2021'
authors = ['Chainflip <https://chainflip.io>']
description = 'Chainflip test utilities used in multiple crates'

[dependencies]
codec = { package = 'parity-scale-codec', version = '3.0.0', default-features = false }

frame-support = { git = "https://github.com/chainflip-io/substrate.git", tag = "chainflip-monthly-2023-07" }
frame-system = { git = "https://github.com/chainflip-io/substrate.git", tag = "chainflip-monthly-2023-07", default-features = false }

sp-io = { git = "https://github.com/chainflip-io/substrate.git", tag = "chainflip-monthly-2023-07" }
sp-core = { git = "https://github.com/chainflip-io/substrate.git", tag = "chainflip-monthly-2023-07" }
sp-runtime = { git = "https://github.com/chainflip-io/substrate.git", tag = "chainflip-monthly-2023-07" }

[dev-dependencies]
scale-info = { version = "2.1.1", features = ["derive"] }

[features]
default = ['std']
std = ['codec/std', 'frame-system/std']
