[package]
name = "cf-test-utilities"
version = "0.1.0"
edition = "2021"
authors = ["Chainflip <https://chainflip.io>"]
description = "Chainflip test utilities used in multiple crates"

[lints]
workspace = true

[dependencies]
codec = { workspace = true, default-features = true }

frame-support = { workspace = true, default-features = true }
frame-system = { workspace = true, default-features = true }

sp-io = { workspace = true, default-features = true }
sp-core = { workspace = true, default-features = true }
sp-runtime = { workspace = true, default-features = true }

[dev-dependencies]
scale-info = { workspace = true, default-features = true, features = [
    "derive",
] }

[features]
std = []
