[toolchain]
channel = "nightly-2025-01-09"
components = [
	"cargo",
	"clippy",
	"rust-analyzer",
	"rust-src",
	"rust-std",
	"rustc",
	"rustfmt",
]
targets = ["wasm32-unknown-unknown"]
profile = "minimal"
