name: Publish npm packages ðŸ›°ï¸

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - packages/cli/**

permissions:
  packages: write
  contents: read

env:
  PACKAGE: "none"

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3

      - name: Check commit message
        run: |
          if [[ "${{ github.event.head_commit.message }}" =~ ^@chainflip-io/cli/v[0-9]+\.[0-9]+\.[0-9]+$ ]]
          then
            echo "PACKAGE=@chainflip-io/cli" >> $GITHUB_ENV
          fi

      - name: Get Node.JS version from .nvmrc
        if: ${{ env.PACKAGE != 'none' }}
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV

      - name: Install pnpm ðŸ’¿
        if: ${{ env.PACKAGE != 'none' }}
        run: npm install -g pnpm@8

      - name: Setup Node ðŸŽ®
        if: ${{ env.PACKAGE != 'none' }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
          registry-url: "https://npm.pkg.github.com"
          scope: "@chainflip-io"

      - name: Install dependencies ðŸšš ðŸ“¦
        if: ${{ env.PACKAGE != 'none' }}
        run: pnpm install

      - name: Build
        if: ${{ env.PACKAGE != 'none' }}
        run: pnpm --filter $PACKAGE build
        working-directory: ./

      - name: Publish npm package ðŸ“¦
        if: ${{ env.PACKAGE != 'none' }}
        run: |
          pnpm --filter $PACKAGE publish
        working-directory: ./
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
