name: Test SDK

on:
  workflow_dispatch: {}
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - packages/sdk/**
  push:
    branches:
      - main
    paths:
      - packages/sdk/**

env:
  FORCE_COLOR: 1
  PACKAGE: "@chainflip-io/chainflip-sdk"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["16", "18"]
    steps:
      - name: Checkout ðŸ
        uses: actions/checkout@v3

      - name: Install pnpm ðŸ’¿
        run: npm install -g pnpm@8

      - name: Setup Node ðŸŽ®
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version}}
          cache: "pnpm"

      - name: Install dependencies ðŸšš ðŸ“¦
        run: pnpm --filter $PACKAGE install

      - name: Run tests
        run: pnpm --filter $PACKAGE test:ci

      - name: Get package name without scope
        run: echo "PACKAGE_WITHOUT_SCOPE=${PACKAGE#*/}" >> "$GITHUB_ENV" # https://stackoverflow.com/a/30865542

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          flags: ${{ env.PACKAGE_WITHOUT_SCOPE }}
          token: ${{ secrets.CF_SDK_CODECOV_TOKEN }} # not required for public repos
