name: Test Swap Service

on:
  workflow_dispatch: {}
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - packages/swap/**
  push:
    branches:
      - main
    paths:
      - packages/swap/**

env:
  FORCE_COLOR: 1
  DB_NAME: "swap"
  DB_USER: "postgres"
  DB_PASS: "postgres"
  DB_PORT: "5432"
  PACKAGE: "swap"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ
        uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV
          echo "DATABASE_URL=postgresql://$DB_USER:$DB_PASS@localhost:$DB_PORT/$DB_NAME?schema=public" >> $GITHUB_ENV

      - name: Docker Compose Action
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: ./packages/swap/docker-compose.yml

      - name: Install pnpm ðŸ’¿
        run: npm install -g pnpm@8

      - name: Setup Node ðŸŽ®
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"

      - name: Install dependencies ðŸšš ðŸ“¦
        run: pnpm --filter $PACKAGE install

      - name: pyenv Build
        uses: gabrielfalcao/pyenv-action@v14
        with:
          default: "3.8"
          command: pip install -U pip # upgrade pip after installing python

      - name: Install dependencies
        run: pip install -r packages/swap/python-client/requirements.txt

      - name: migrate database
        run: pnpm --filter $PACKAGE exec pnpm prisma migrate dev

      - name: Run tests
        run: pnpm --filter $PACKAGE test:ci

      - name: Get package name without scope
        run: echo "PACKAGE_WITHOUT_SCOPE=${PACKAGE#*/}" >> "$GITHUB_ENV" # https://stackoverflow.com/a/30865542

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          flags: ${{ env.PACKAGE_WITHOUT_SCOPE }}
          token: ${{ secrets.CF_SDK_CODECOV_TOKEN }} # not required for public repos