
[package]
name = "witness-fetch-rpc"
version = "2.0.0"
edition = "2018"
authors = ['Chainflip Team']
repository = 'https://github.com/chainflip-io/chainflip-test-state-chain'
description = "A pallet for the cf-transactions RPC"
license = "GPL-3.0-or-later"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.0" }
jsonrpc-core = "15.0"
jsonrpc-core-client = "15.0"
jsonrpc-derive = "15.0"
serde = { version = "1.0", features = ["derive"], optional = true }

# Substrate packages

sp-api = { version = '2.0.0', default-features = false }
sp-blockchain = { version = '2.0.0', default-features = false}
sp-rpc = { version = '2.0.0', default-features = false}
sp-runtime = { version = '2.0.0', default-features = false}
frame-support = { default-features = false, version = '2.0.0' }
frame-system = { default-features = false, version = '2.0.0' }

# local packages
witness-fetch-runtime-api = { version = "2.0.0", path = "../runtime-api", default-features = false }

[dev-dependencies]
sp-core = { default-features = false, version = '2.0.0' }
sp-io = { default-features = false, version = '2.0.0' }

[features]
default = ["std"]
std = [
  "serde",
  "sp-api/std",
  "sp-runtime/std",
  "frame-support/std",
  "frame-system/std",
  "witness-fetch-runtime-api/std"
]