[package]
authors = ["Chainflip team <https://github.com/chainflip-io>"]
edition = '2021'
name = "engine-upgrade-utils"
version = "1.0.0"

[dependencies]
anyhow = { workspace = true }
toml = { workspace = true }
