[package]
name = "scale-json-event-logger"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.3"
scale-info = "2.10"
log = "0.4.16"
subxt = { version = "0.33", features = ["substrate-compat"] }
tokio = { version = "1.22", features = ["full"] }
cf-utilities = { package = "utilities", path = ".." }
hex = "0.4.3"
hex-literal = "0.4.1"
anyhow = "1.0"

[features]
std = [
	"log/std"
]
