[package]
name = "cf-amm"
version = "0.1.0"
authors = ['Chainflip <https://chainflip.io>']
edition = '2021'
description = "Chainflip's AMM Logic"

[dependencies]
cf-primitives = { path = '../primitives', default-features = false }
cf-utilities = { package = 'utilities', path = '../../utilities', default-features = false }
serde = { version = '1.0', default-features = false, features = [
	'alloc',
	'derive',
] }

# Parity deps
codec = { package = 'parity-scale-codec', version = '3.6.1', default-features = false, features = [
	'derive',
] }
scale-info = { version = '2.5.0', default-features = false, features = [
	'derive',
] }

sp-core = { git = "https://github.com/chainflip-io/polkadot-sdk.git", tag = "chainflip-substrate-1.1+2", default-features = false }
sp-std = { git = "https://github.com/chainflip-io/polkadot-sdk.git", tag = "chainflip-substrate-1.1+2", default-features = false }

[dev-dependencies]
rand = "0.8"

[features]
default = ['std']
slow-tests = []
std = [
	'cf-primitives/std',
	'cf-utilities/std',
	'codec/std',
	'scale-info/std',
	'sp-core/std',
	'sp-std/std',
	'serde/std',
]
