[package]
name = "ethereum-eip712"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
codec = { workspace = true, features = ["derive"] }
ethabi = { workspace = true }
hex = { package = "const-hex", version = "1.6", features = [
    "hex",
    "alloc",
], default-features = false }
scale-info = { workspace = true, features = ["derive"] }
scale-value = { workspace = true }
serde = { workspace = true, features = ["derive", "alloc"] }
serde_json = { workspace = true, features = ["alloc"] }
sp-std = { workspace = true }
tiny-keccak = { version = "2.0.2", features = [
    "keccak",
], default-features = false }
unicode-xid = { version = "0.2", features = ["no_std"] }
ethers-core = { workspace = true, optional = true }

[dev-dependencies]
ethers-core = { workspace = true }
cf-utilities = { workspace = true, default-features = true, features = [
    "test-utils",
] }

[features]
default = ["std"]
std = [
    "codec/std",
    "ethabi/std",
    "hex/std",
    "scale-info/std",
    "serde_json/std",
    "sp-std/std",
    "ethers-core",
]
