[package]
name = "generic-typeinfo-derive"
version = "0.1.0"
edition = "2021"

[dependencies]
const_format = "0.2.33"
proc-macro2 = "1.0.89"
quote.workspace = true
syn.workspace = true

[lints]
workspace = true

[lib]
proc-macro = true
