[package]
name = 'cf-runtime-upgrade-utilities'
version = '0.1.0'
edition = '2021'
authors = ['Chainflip <https://chainflip.io>']
description = 'Chainflip utilities for runtime upgrades.'

[dependencies]
log = { version = '0.4.16', default-features = false }

sp-std = { git = "https://github.com/chainflip-io/substrate.git", tag = "chainflip-monthly-2022-12", default-features = false }
frame-support = { git = "https://github.com/chainflip-io/substrate.git", tag = "chainflip-monthly-2022-12", default-features = false }
sp-io = { git = "https://github.com/chainflip-io/substrate.git", tag = "chainflip-monthly-2022-12" }

[features]
default = ['std']
std = [
  'frame-support/std',
  'log/std',
  'sp-std/std',
]
try-runtime = ['frame-support/try-runtime']