[package]
name = 'cf-runtime-upgrade-utilities'
version = '0.1.0'
edition = '2021'
authors = ['Chainflip <https://chainflip.io>']
description = 'Chainflip utilities for runtime upgrades.'

[dependencies]
log = { version = '0.4.14', default-features = false }

[dependencies.sp-std]
default-features = false
git = 'https://github.com/chainflip-io/substrate.git'
tag = 'chainflip-monthly-2022-06'

[dependencies.frame-support]
default-features = false
git = 'https://github.com/chainflip-io/substrate.git'
tag = 'chainflip-monthly-2022-06'

[dev-dependencies.sp-io]
git = 'https://github.com/chainflip-io/substrate.git'
tag = 'chainflip-monthly-2022-06'

[features]
default = ['std']
std = [
  'frame-support/std',
  'log/std',
  'sp-std/std',
]
try-runtime = ['frame-support/try-runtime']