[package]
name = "solana-rpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.49"
bs58 = "^0.5"
base64 = "^0.21"
jsonrpsee = {version = "^0.20.3", features = ["http-client", "ws-client", "client-ws-transport-webpki-tls"]}
serde = {version = "^1", features = ["derive"]}
serde_json = "1.0"
thiserror = "1.0.26"

[dev-dependencies]
tokio = {version = "^1", features = ["macros", "rt", "rt-multi-thread"]}