[package]
authors = ["Chainflip team <https://github.com/chainflip-io>"]
name = "chainflip-lp"
version = "0.1.0"
edition = "2021"

[package.metadata.deb]
depends = "$auto, systemd"
extended-description = """\
Chainflip Liquidity Provider API Rpc Server"""
maintainer = "Chainflip Labs GmbH <dev@chainflip.io>"
name = "chainflip-lp"
priority = "required"
section = "rust"
maintainer-scripts = "package/"
systemd-units = {enable = false}
assets = [
  ["target/release/chainflip-lp", "usr/bin/", "755"],
]

[[bin]]
name = "chainflip-lp"

[dependencies]
chainflip-api = { path = "../../lib" }

anyhow = "1.0.66"
clap = { version = "3.2.23", features = ["derive"] }
hex = "0.4.3"
jsonrpsee = { version = "0.16.2", features = ["full"]}
tokio = "1.20.1"
tracing = "0.1.34"
tracing-subscriber = { version = "0.3.3", features = ["env-filter"] }
serde_json = "1.0"