[package]
name = 'multisig-p2p-transport'
version = '0.1.0'
authors = ['Chainflip Team <https://github.com/chainflip-io>']
edition = '2021'

[dependencies]
anyhow = '1.0'
bincode = '1.3.3'
serde = {version = '1.0.125', features = ['derive']}
log = '0.4.16'
jsonrpc-core = '18.0.0'
jsonrpc-core-client = '18.0.0'
jsonrpc-derive = '18.0.0'
serde_json = '1.0.68'
bs58 = '0.4.0'
futures = { version = '0.3.4', features = ['compat'] }
tokio = {version = '1.13.1', features = ['full']}
async-trait = '0.1.49'
ipc-channel = '0.16.0'
scopeguard = '1.1.0'

cf-utilities = { package = 'utilities', path = '../../utilities' }

[dependencies.sp-runtime]
git = 'https://github.com/chainflip-io/substrate.git'
tag = 'chainflip-monthly-2022-06'

[dependencies.sc-network]
git = 'https://github.com/chainflip-io/substrate.git'
tag = 'chainflip-monthly-2022-06'

[dependencies.sp-core]
git = 'https://github.com/chainflip-io/substrate.git'
tag = 'chainflip-monthly-2022-06'

[dependencies.sc-rpc]
git = 'https://github.com/chainflip-io/substrate.git'
tag = 'chainflip-monthly-2022-06'
features = ['test-helpers']

[dependencies.sc-service]
features = ['wasmtime']
git = 'https://github.com/chainflip-io/substrate.git'
tag = 'chainflip-monthly-2022-06'

[dev-dependencies]
predicates = '2.1.1'
mockall = '0.11.0'
tokio-stream = '0.1.5'
