[package]
authors = ['Chainflip Team <https://github.com/chainflip-io>']
description = 'FRAME pallet template for transaction broadcast flow with the CFE.'
edition = '2018'
homepage = 'https://chainflip.io'
license = '<TODO>'
name = 'pallet-cf-transaction-broadcast'
repository = 'https://github.com/chainflip-io/chainflip-backend'
version = '0.1.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
cf-traits = { path = "../../traits", default-features = false }
codec = { default-features = false, features = ['derive'], package = 'parity-scale-codec', version = '2.0.0' }
frame-system = { default-features = false, version = '3.0.0' }
frame-support = { default-features = false, version = '3.0.0' }
frame-benchmarking = { default-features = false, optional = true, version = '3.1.0' }
sp-core = { default-features = false, version = '3.0.0' }
sp-runtime = { default-features = false, version = '3.0.0' }
sp-std = { default-features = false, version = '3.0.0' }

# Ethereum transaction encoding
ethabi = {default-features = false, features = ['codec'], git = 'https://github.com/chainflip-io/ethabi', rev = 'bfa7866'}
ethereum = {default-features = false, version = "0.9"}
hex = {default-features = false, version = "0.4"}
rlp = {default-features = false, version = "0.5"}

[dev-dependencies]
serde = { version = "1.0.119" }
sp-io = { default-features = false, version = '3.0.0' }

[features]
default = ['std']
std = [
  'cf-traits/std',
  'codec/std',
  'hex/std',
  'frame-support/std',
  'frame-system/std',
  'frame-benchmarking/std',
  'sp-core/std',
  'sp-runtime/std',
  'sp-std/std',
  'ethabi/std',
  'ethereum/std',
  'rlp/std',
]
runtime-benchmarks = [
	'frame-benchmarking',
	'frame-support/runtime-benchmarks',
	'frame-system/runtime-benchmarks',
]
# Note: frame-support `try-runtime` feature is released after v3.
#   Uncomment the following line when `frame-support` version > `3.0.0`.
# try-runtime = ['frame-support/try-runtime']
