# PLEASE READ
# Any changes made to this file must be first approved by a member of the Platform team.

# Default configurations for the CFE
[node_p2p]
node_key_file = "node_key_file"
ip_address = "IP_ADDRESS"
port = "8078"

[state_chain]
# 32 byte hex secret key - associated with the node's public id (public key)
signing_key_file = "signing_key_file"
ws_endpoint = "ws://localhost:9944"

[eth]
# Ethereum private key file path. Default is the docker secrets path. This file should contain a hex-encoded private key.
private_key_file = "eth_private_key_file"

[health_check]
hostname = "0.0.0.0"
port = 5555

[signing]
db_file = "data.db"
