# Default configurations for the CFE

[message_queue]
# can also be IP
hostname = "localhost"
port = "4222"

[state_chain]
hostname = "localhost"
port = "9944"

[eth]
hostname = "localhost"
port = "8545"
# Address used on the Ganache/Brownie tests
stake_manager_eth_address = "0xEAd5De9C41543E4bAbB09f9fE4f79153c036044f"
key_manager_eth_address = "0xdBa9b6065Deb6Cc057BC779fF6736709ecBa3409"

[health_check]
hostname = "0.0.0.0"
port = 5555
