# Default configurations for the CFE
[node_p2p]
node_key_file = "/run/secrets/node_key_file"
ip_address = "0.0.0.0"
port = 8078

[state_chain]
# 32 byte hex secret key - associated with the node's public id (public key)
signing_key_file = ""
ws_endpoint = "ws://localhost:9944"

[eth]
# Ethereum private key file path. Default is the docker secrets path. This file should contain a hex-encoded private key.
private_key_file = "/run/secrets/eth_private_key"

[dot]
# NB: You will need to manually add :443 to the url provided by the provider, as jsonrpsee wants one.
ws_node_endpoint = "wss://my_fake_polkadot_rpc:443/<secret_key>"

[health_check]
hostname = "0.0.0.0"
port = 5555

[signing]
db_file = "data.db"
