# Testing configurations for the CFE

[message_queue]
# can also be IP
endpoint = "http://localhost:4222"

[state_chain]
p2p_private_key_file = "./tests/test_keystore/p2p_key"
signing_key_file = "./tests/test_keystore/alice_key"
ws_endpoint = "ws://localhost:9944"

[eth]
from_block = 0
node_endpoint = "wss://network.my_eth_node:80/<secret_key>"
# Ethereum private key file path. Default is the docker secrets path. This file should contain a hex-encoded private key.
private_key_file = "/run/secrets/eth_private_key"
# Address used on the Ganache/Brownie tests
key_manager_eth_address = "0xdBa9b6065Deb6Cc057BC779fF6736709ecBa3409"
stake_manager_eth_address = "0xEAd5De9C41543E4bAbB09f9fE4f79153c036044f"

[health_check]
hostname = "127.0.0.1"
port = 5555

[signing]
db_file = "data.db"
genesis_validator_ids = [
  [212, 53, 147, 199, 21, 253, 211, 28, 97, 20, 26, 189, 4, 169, 159, 214, 130, 44, 133, 88, 133, 76, 205, 227, 154, 86, 132, 231, 165, 109, 162, 125],
]
