# Testing configurations for the CFE

[state_chain]
# 32 byte hex secret key - associated with the node's public id (public key)
signing_key_file = "./tests/test_keystore/alice_key"
ws_endpoint = "ws://localhost:9944"

[eth]
from_block = 0
node_endpoint = "ws://localhost:8545"
# Ethereum private key file path. Default is the docker secrets path. This file should contain a hex-encoded private key.
private_key_file = "/run/secrets/eth_private_key"
# Address used on the Ganache/Brownie tests
key_manager_eth_address = "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512"
stake_manager_eth_address = "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9"

# unused by snow white
[health_check]
hostname = "127.0.0.1"
port = 5555

# Unused by Snowwhite
[signing]
db_file = "data.db"
