# Testing configurations for the CFE

[message_queue]
# can also be IP
hostname = "localhost"
port = "4222"

[state_chain]
hostname = "localhost"
port = "9944"
signing_key_path = "./tests/test_keystore/alice_key"

[eth]
hostname = "localhost"
port = "8545"
# Ethereum private key file path. Default is the docker secrets path. This file should contain a hex-encoded private key.
private_key_file = "/run/secrets/eth_private_key"
# Address used on the Ganache/Brownie tests
key_manager_eth_address = "0xdBa9b6065Deb6Cc057BC779fF6736709ecBa3409"
stake_manager_eth_address = "0xEAd5De9C41543E4bAbB09f9fE4f79153c036044f"

[health_check]
hostname = "127.0.0.1"
port = 5555

[signing]
init_validator_ids = [
  "alice",
  "bob",
]
