# Testing configurations for the CFE

[message_queue]
# can also be IP
hostname = "localhost"
port = "4222"

[state_chain]
hostname = "test"
port = "80"

[eth]
hostname = "localhost"
port = "8545"
# Address used on the Ganache/Brownie tests
stake_manager_eth_address = "0xEAd5De9C41543E4bAbB09f9fE4f79153c036044f"

[engine]
health_check_port = 5555
