# Testing configurations for the CFE

[state_chain]
p2p_private_key_file = "./tests/test_keystore/p2p_key"
signing_key_file = "./tests/test_keystore/alice_key"
ws_endpoint = "ws://localhost:9944"

[eth]
from_block = 0
node_endpoint = "ws://localhost:8545"
# Ethereum private key file path. Default is the docker secrets path. This file should contain a hex-encoded private key.
private_key_file = "/run/secrets/eth_private_key"
# Address used on the Ganache/Brownie tests
key_manager_eth_address = "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512"
stake_manager_eth_address = "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9"

[health_check]
hostname = "127.0.0.1"
port = 5555

[signing]
db_file = "data.db"
genesis_validator_ids = [
  [212, 53, 147, 199, 21, 253, 211, 28, 97, 20, 26, 189, 4, 169, 159, 214, 130, 44, 133, 88, 133, 76, 205, 227, 154, 86, 132, 231, 165, 109, 162, 125], # alice
]
