[package]
authors = ["Kyle Zsembery <zsembery.kyle@gmail.com>"]
edition = "2018"
name = "chainflip-cli"
version = "0.1.0"

[dependencies]
anyhow = "1.0"
chainflip-engine = {path = "../../engine/"}
config = "0.11.0"
futures = "0.3.14"
hex = "0.4.3"
serde = {version = "1.0", features = ["derive", "rc"]}
slog = {version = "2.7.0", features = ["max_level_trace", "release_max_level_trace"]}
structopt = "0.3.23"
tokio = {version = "1.5.0", features = ["full"]}

# State chain
pallet-cf-staking = {path = "../../state-chain/pallets/cf-staking"}
pallet-cf-threshold-signature = {path = "../../state-chain/pallets/cf-threshold-signature"}
state-chain-runtime = {path = "../../state-chain/runtime"}
