on:
  workflow_call:
    inputs:
      version:
        description: Release version
        required: true
        type: string

permissions:
  id-token: write
  contents: read
jobs:
  upload:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout ğŸ›’
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Download Artifacts ğŸ“¥
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a
        with:
          name: chainflip-backend-bin
          path: chainflip-backend-bin

      - name: Download M2 binaries ğŸ“¥
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a
        with:
          name: chainflip-backend-bin-mac-m2
          path: chainflip-backend-bin-mac-m2

      - name: Move shared library files ğŸ“‚
        run: |
          mkdir -p /tmp/chainflip-engine-shared-libs/
          mv chainflip-backend-bin/libchainflip_engine_v*.so /tmp/chainflip-engine-shared-libs/
          mv chainflip-backend-bin-mac-m2/libchainflip_engine_v*.dylib /tmp/chainflip-engine-shared-libs

      - name: Debug ğŸ›
        run: |
          ls -la chainflip-backend-bin
          ls -la chainflip-backend-bin-mac-m2

      - name: Configure AWS credentials using OIDC ğŸªª
        uses: aws-actions/configure-aws-credentials@010d0da01d0b5a38af31e9c3470dbfdabdecca3a
        with:
          aws-region: eu-central-1
          role-to-assume: arn:aws:iam::962042992619:role/chainflip-github-bot

      - name: Upload engine shared libraries S3 ğŸš€
        run: |
          aws s3 cp /tmp/chainflip-engine-shared-libs/ s3://repo.chainflip.io/releases/${{ inputs.version }} --recursive
