name: Check Helm Charts ðŸ“‹
on:
  pull_request:
    paths:
      - charts/**
env:
  FORCE_COLOR: 1

jobs:
  check-helm-charts:
    strategy:
      matrix:
        chart: [chainflip-broker-api]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ
        uses: actions/checkout@v3

      - name: Download dependencies ðŸ’¾
        working-directory: charts/${{ matrix.chart }}
        run: helm dependency update

      - name: Linting ${{ matrix.chart }} ðŸ“
        run: >
          helm lint
          charts/${{ matrix.chart }}